<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishTrimmed>false</PublishTrimmed>
    <WasmEnableWebcil>false</WasmEnableWebcil>
    <WasmFingerprintDotnetJs>false</WasmFingerprintDotnetJs>
    <WasmInitialHeapSize>268435456</WasmInitialHeapSize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\upstream\pascalabcnet\Compiler\Compiler.csproj" />
    <ProjectReference Include="..\..\upstream\pascalabcnet\PascalABCLanguageInfo\PascalABCLanguageInfo.csproj" />
    <ProjectReference Include="..\PascalABC.Web.Graphics\PascalABC.Web.Graphics.csproj" />
  </ItemGroup>
</Project>
